<?php
/**
 * intrabuild
 * (c) 2002-2008 siteartwork.de/MindPatterns
 * license@siteartwork.de
 *
 * $Author$
 * $Id$
 * $Date$ 
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$ 
 */
?>

<!DOCTYPE htmlPUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
    <title>intraBuild 2.0 - fehler</title>

    
</head>

<body>
 <h1>Es ist ein fehler aufgetreten!</h1>
 
 <strong>code: </strong><?php echo $this->error->code; ?><br />
 <strong>file: </strong><?php echo $this->error->file; ?><br />
 <strong>line: </strong><?php echo $this->error->line; ?><br />
 <strong>message: </strong><?php echo $this->error->message; ?><br />
 <strong>type: </strong><?php echo $this->error->type; ?><br />
    
</body>
</html>