<?php
/**
 * conjoon
 * (c) 2002-2012 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<!DOCTYPE htmlPUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
    <title><?php echo $this->title; ?></title>


</head>

<body>
 <h1>Sorry, I couldn't process your request. Something odd happened.</h1>

 <strong>code: </strong><?php echo $this->error->code; ?><br />
 <strong>file: </strong><?php echo $this->error->file; ?><br />
 <strong>line: </strong><?php echo $this->error->line; ?><br />
 <strong>message: </strong><?php echo $this->error->message; ?><br />
 <strong>type: </strong><?php echo $this->error->type; ?><br />

</body>
</html>