<?php
/**
 * intrabuild
 * (c) 2002-2008 siteartwork.de/MindPatterns
 * license@siteartwork.de
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<!-- ########################################################################################## -->

<!-- base -->
<script type="text/javascript" src="/js/extjs/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="/js/extjs/ext-all-debug.js"></script>
<!-- ^^ EO base -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="./ext-config.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="/js/intrabuild/source/Overrides.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load Gettext since other sources may depend on it -->
<script type="text/javascript" src="/js/intrabuild/source/Gettext.js"></script>
<!-- ^^ EO Load Gettext since other sources may depend on it -->

<!-- de.intrabuild.util -->
<script type="text/javascript" src="/js/intrabuild/source/util/Record.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/util/Dom.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/util/MimeIconFactory.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/util/Json.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/util/Registry.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/util/PreLoader.js"></script>
<!-- ^^ EO de.intrabuild.util -->

<!-- Ext.ux.Media -->
<script type="text/javascript" src="/js/ext-ux-media/uxmedia.js"></script>
<script type="text/javascript" src="/js/ext-ux-media/uxflash.js"></script>
<!-- ^^ EO Ext.ux.Media -->

<!-- Ext.ux.YoutubePlayer -->
<script type="text/javascript" src="/js/ext-ux-youtubeplayer/YoutubePlayer.js"></script>
<script type="text/javascript" src="/js/ext-ux-youtubeplayer/YoutubePlayerControl.js"></script>
<!-- ^^ EO Ext.ux.YoutubePlayer -->

<!-- Ext.ux.util.Messagebus -->
<script type="text/javascript" src="/js/ext-ux-util-messagebus/MessageBus.js"></script>
<!-- ^^ EO Ext.ux.util.Messagebus -->

<!-- Ext.ux.ToastWindow -->
<script type="text/javascript" src="/js/ext-ux-toastwindow/ToastWindow.js"></script>
<!-- ^^ EO Ext.ux.ToastWindow -->

<!-- Ext.ux.layout.CardLayout -->
<script type="text/javascript" src="/js/ext-ux-layout-cardlayout/CardLayout.js"></script>
<!-- ^^ EO Ext.ux.layout.CardLayout -->

<!-- Ext.ux.Wiz -->
<script type="text/javascript" src="/js/ext-ux-wiz/Wizard.js"></script>
<script type="text/javascript" src="/js/ext-ux-wiz/Header.js"></script>
<script type="text/javascript" src="/js/ext-ux-wiz/Card.js"></script>
<!-- ^^ EO Ext.ux.Wiz -->

<!-- Ext.ux.LiveGrid -->
<script type="text/javascript" src="/js/ext-ux-livegrid/BufferedGridView.js"></script>
<script type="text/javascript" src="/js/ext-ux-livegrid/BufferedRowSelectionModel.js"></script>
<script type="text/javascript" src="/js/ext-ux-livegrid/BufferedStore.js"></script>
<script type="text/javascript" src="/js/ext-ux-livegrid/BufferedGridDragZone.js"></script>
<script type="text/javascript" src="/js/ext-ux-livegrid/BufferedGridToolbar.js"></script>
<script type="text/javascript" src="/js/ext-ux-livegrid/BufferedJsonReader.js"></script>
<!-- ^^ EO Ext.ux.LiveGrid -->

<!-- de.intrabuild.form -->
<script type="text/javascript" src="/js/intrabuild/source/form/TextField.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/form/TextArea.js"></script>
<!-- ^^ EO de.intrabuild.form  -->

<!-- de.intrabuild.groupware.ResponseInspector -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/ResponseInspector.js"></script>
<!-- ^^ EO de.intrabuild.groupware.ResponseInspector -->

<!-- de.intrabuild.groupware.reception -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/Reception.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/reception/LogoutWindow.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/reception/LoginWindow.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/reception/StateIndicator.js"></script>
<!-- ^^ EO de.intrabuild.groupware.reception -->

<!-- de.intrabuild.groupware -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/StatusBar.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/ToolbarManager.js"></script>
<!-- ^^ EO de.intrabuild.groupware -->

<!-- de.intrabuild.groupware.util -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/util/LinkInterceptor.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/util/FormIntro.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/util/Clear.js"></script>
<!-- ^^ EO de.intrabuild.groupware.util -->

<!-- de.intrabuild.groupware.forms -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/forms/QuickContactFormFieldConfigs.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/forms/QuickContactForm.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/forms/QuickEmailFormFieldConfigs.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/forms/QuickEmailForm.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/QuickEditPanel.js"></script>
<!-- ^^ EO de.intrabuild.groupware.forms -->

<!-- de.intrabuild.groupware.feeds -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/ItemRecord.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/AccountRecord.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/FeedStore.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/FeedRunner.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/AccountStore.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/FeedViewBaton.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/FeedPreview.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/FeedGrid.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/AddFeedDialog.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/feeds/FeedOptionsDialog.js"></script>
<!-- ^^ EO de.intrabuild.groupware.feeds -->

<!-- de.intrabuild.groupware.email -->

<script type="text/javascript" src="/js/intrabuild/source/groupware/email/AccountRecord.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/AccountStore.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailRecord.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailItemRecord.js"></script>

<script type="text/javascript" src="/js/intrabuild/source/groupware/email/decorator/AccountActionComp.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/FetchMenuButton.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailEditorManager.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailViewBaton.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailAccountDialog.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailAccountWizard.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/view/DefaultViewRenderer.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailViewPanel.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailPanel.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailGrid.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailTree.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailTreeLoader.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/EmailPreview.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/NodeContextMenu.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/NodeEditor.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/PendingNodeItemRecord.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/PendingNodeUI.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/LatestEmailsPanel.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/email/Letterman.js"></script>
<!-- ^^ EO de.intrabuild.groupware.email -->