<?php
/**
 * conjoon
 * (c) 2002-2009 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<?php /*@BUILD_ACTIVE@

<script type="text/javascript" src="./js/extjs/ext-base.js"></script>
<script type="text/javascript" src="./js/extjs/ext-all.js"></script>

<script type="text/javascript" src="./js/ext-ux-media/uxmedia.js"></script>
<script type="text/javascript" src="./js/ext-ux-media/uxflash.js"></script>

<script type="text/javascript" src="./js/conjoon/conjoon-all.js"></script>

@BUILD_ACTIVE@*/ ?>

<?php /*@REMOVE@*/ ?>
<!-- base -->
<script type="text/javascript" src="/js/extjs/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="/js/extjs/ext-all-debug.js"></script>
<!-- ^^ EO base -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="./ext-config.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="/js/conjoon/source/Overrides.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load Gettext since other sources may depend on it -->
<script type="text/javascript" src="/js/conjoon/source/Gettext.js"></script>
<!-- ^^ EO Load Gettext since other sources may depend on it -->

<!-- com.conjoon.util -->
<script type="text/javascript" src="/js/conjoon/source/util/Format.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/Record.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/Dom.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/MimeIconFactory.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/Json.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/Registry.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/PreLoader.js"></script>
<!-- ^^ EO com.conjoon.util -->

<!-- Ext.ux.Media -->
<script type="text/javascript" src="/js/ext-ux-media/uxmedia.js"></script>
<script type="text/javascript" src="/js/ext-ux-media/uxflash.js"></script>
<!-- ^^ EO Ext.ux.Media -->

<!-- Ext.ux.YoutubePlayer -->
<script type="text/javascript" src="/js/ext-ux-youtubeplayer/YoutubePlayer.js"></script>
<script type="text/javascript" src="/js/ext-ux-youtubeplayer/YoutubePlayerControl.js"></script>
<!-- ^^ EO Ext.ux.YoutubePlayer -->

<!-- Ext.ux.util.Messagebus -->
<script type="text/javascript" src="/js/ext-ux-util-messagebus/MessageBus.js"></script>
<!-- ^^ EO Ext.ux.util.Messagebus -->

<!-- Ext.ux.ToastWindow -->
<script type="text/javascript" src="/js/ext-ux-toastwindow/ToastWindow.js"></script>
<!-- ^^ EO Ext.ux.ToastWindow -->

<!-- Ext.ux.layout.CardLayout -->
<script type="text/javascript" src="/js/ext-ux-layout-cardlayout/CardLayout.js"></script>
<!-- ^^ EO Ext.ux.layout.CardLayout -->

<!-- Ext.ux.Wiz -->
<script type="text/javascript" src="/js/ext-ux-wiz/Wizard.js"></script>
<script type="text/javascript" src="/js/ext-ux-wiz/Header.js"></script>
<script type="text/javascript" src="/js/ext-ux-wiz/Card.js"></script>
<!-- ^^ EO Ext.ux.Wiz -->

<!-- Ext.ux.grid.GridViewMenuPlugin -->
<script type="text/javascript" src="/js/ext-ux-grid-gridviewmenuplugin/GridViewMenuPlugin.js"></script>
<!-- ^^ EO Ext.ux.grid.GridViewMenuPlugin -->

<!-- Ext.ux.LiveGrid -->
<script type="text/javascript" src="/js/ext-ux-livegrid/livegrid-all.js"></script>
<!-- ^^ EO Ext.ux.LiveGrid -->

<!-- com.conjoon.groupware.workbench -->
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/Menubar.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/BookmarkController.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/ToolbarController.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/ContentPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/Workbench.js"></script>
<!-- ^^ EO com.conjoon.groupware.workbench -->


<!-- com.conjoon.form -->
<script type="text/javascript" src="/js/conjoon/source/form/TextField.js"></script>
<script type="text/javascript" src="/js/conjoon/source/form/TextArea.js"></script>
<!-- ^^ EO com.conjoon.form  -->

<!-- com.conjoon.groupware.ResponseInspector -->
<script type="text/javascript" src="/js/conjoon/source/groupware/ResponseInspector.js"></script>
<!-- ^^ EO com.conjoon.groupware.ResponseInspector -->

<!-- com.conjoon.groupware.Registry -->
<script type="text/javascript" src="/js/conjoon/source/groupware/Registry.js"></script>
<!-- ^^ EO com.conjoon.groupware.ResponseInspector -->


<!-- com.conjoon.groupware.reception -->
<script type="text/javascript" src="/js/conjoon/source/groupware/Reception.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/reception/LogoutWindow.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/reception/LoginWindow.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/reception/StateIndicator.js"></script>
<!-- ^^ EO com.conjoon.groupware.reception -->

<!-- com.conjoon.groupware -->
<script type="text/javascript" src="/js/conjoon/source/groupware/StatusBar.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/ToolbarManager.js"></script>
<!-- ^^ EO com.conjoon.groupware -->

<!-- com.conjoon.groupware.util -->
<script type="text/javascript" src="/js/conjoon/source/groupware/util/LinkInterceptor.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/util/FormIntro.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/util/Clear.js"></script>
<!-- ^^ EO com.conjoon.groupware.util -->

<!-- com.conjoon.groupware.forms -->
<script type="text/javascript" src="/js/conjoon/source/groupware/forms/QuickContactFormFieldConfigs.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/forms/QuickContactForm.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/forms/QuickEmailFormFieldConfigs.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/forms/QuickEmailForm.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/QuickEditPanel.js"></script>
<!-- ^^ EO com.conjoon.groupware.forms -->

<!-- com.conjoon.groupware.home -->
<script type="text/javascript" src="/js/conjoon/source/groupware/home/HomePanel.js"></script>
<!-- ^^ EO com.conjoon.groupware.home -->

<!-- com.conjoon.groupware.feeds -->
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/ItemRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/AccountRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedRunner.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/AccountStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedViewBaton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedPreview.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedGrid.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/AddFeedDialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedOptionsDialog.js"></script>
<!-- ^^ EO com.conjoon.groupware.feeds -->

<!-- com.conjoon.groupware.email -->

<script type="text/javascript" src="/js/conjoon/source/groupware/email/view/GridViewMenuPlugin.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/data/DefaultColumnModel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/data/Draft.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/Dispatcher.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/AccountRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/AccountStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailItemRecord.js"></script>

<script type="text/javascript" src="/js/conjoon/source/groupware/email/decorator/AccountActionComp.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/FetchMenuButton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/form/RecipientComboBox.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailEditorManager.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailViewBaton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailAccountDialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailAccountWizard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/view/DefaultViewRenderer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailViewPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/view/EmailGridRowRenderer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailGrid.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailTree.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailTreeLoader.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailPreview.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/NodeContextMenu.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/NodeEditor.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/PendingNodeItemRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/PendingNodeUI.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/LatestEmailsPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/Letterman.js"></script>
<!-- ^^ EO com.conjoon.groupware.email -->

<!-- STARTUP -->
<script type="text/javascript" src="./startup.js"></script>
<!-- ^^ EO STARTUP -->
<?php /*@REMOVE@*/ ?>