<?php
/**
 * conjoon
 * (c) 2002-2012 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<?php /*@BUILD_ACTIVE@

<script type="text/javascript" src="./js/extjs/ext-base.js"></script>
<script type="text/javascript" src="./js/extjs/ext-all.js"></script>
<script type="text/javascript" src="./js/conjoon/conjoon-all.js"></script>

@BUILD_ACTIVE@*/ ?>

<script type="text/javascript">

    // this object's purpose is to provide some basic informations about the app
    // in case this page was loaded over the AppCache and the data could not be
    // retrieved using the registry.
    var appCacheFallback = {
            softwareLabel : "<?php echo $this->softwareLabel; ?>",
            editionLabel  : "<?php echo $this->editionLabel; ?>",
            versionLabel  : "<?php echo $this->versionLabel; ?>"
    };

</script>


<?php /*@REMOVE@*/ ?>
<!-- base -->
<script type="text/javascript" src="/js/extjs/adapter/ext/ext-base-debug.js"></script>
<script type="text/javascript" src="/js/extjs/ext-all-debug.js"></script>
<!-- ^^ EO base -->

<!-- Load common bug overrides for Ext JS -->
<script type="text/javascript" src="/js/conjoon/source/ext-bug-overrides.js"></script>
<!-- ^^ EO Load common bug overrides for Ext JS  -->


<!-- Load common overrides for the project -->
<script type="text/javascript" src="./ext-config.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="/js/conjoon/source/Overrides.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load Gettext since other sources may depend on it -->
<script type="text/javascript" src="/js/conjoon/source/Gettext.js"></script>
<!-- ^^ EO Load Gettext since other sources may depend on it -->

<!-- Load SystemMessage-classes -->
<script type="text/javascript" src="/js/conjoon/source/SystemMessage.js"></script>
<script type="text/javascript" src="/js/conjoon/source/SystemMessageManager.js"></script>
<!-- ^^ EO Load SystemMessage-classes -->

<!-- com.conjoon.util -->
<script type="text/javascript" src="/js/conjoon/source/util/Format.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/Record.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/Dom.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/MimeIconFactory.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/Json.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/Registry.js"></script>
<script type="text/javascript" src="/js/conjoon/source/util/PreLoader.js"></script>
<!-- ^^ EO com.conjoon.util -->

<!-- Ext.ux.FlexAccord -->
<script type="text/javascript" src="/js/ext-ux-flexaccord/flexaccord-all-debug.js"></script>
<!-- ^^ EO Ext.ux.FlexAccord -->

<!-- Ext.ux.FlashControl -->
<script type="text/javascript" src="/js/ext-ux-flashcontrol/flashcontrol-all-debug.js"></script>
<!-- ^^ EO Ext.ux.FlashControl -->

<!-- Ext.ux.YoutubePlayer -->
<script type="text/javascript" src="/js/ext-ux-youtubeplayer/YoutubePlayer.js"></script>
<script type="text/javascript" src="/js/ext-ux-youtubeplayer/YoutubePlayerControl.js"></script>
<!-- ^^ EO Ext.ux.YoutubePlayer -->

<!-- Ext.ux.util.Messagebus -->
<script type="text/javascript" src="/js/ext-ux-util-messagebus/MessageBus.js"></script>
<!-- ^^ EO Ext.ux.util.Messagebus -->

<!-- Ext.ux.ToastWindow -->
<script type="text/javascript" src="/js/ext-ux-toastwindow/ToastWindow.js"></script>
<!-- ^^ EO Ext.ux.ToastWindow -->

<!-- Ext.ux.layout -->
<script type="text/javascript" src="/js/ext-ux-layout-slidelayout/SlideLayout.js"></script>
<!-- ^^ EO Ext.ux.layout -->

<!-- Ext.ux.Wiz -->
<script type="text/javascript" src="/js/ext-ux-wiz/Wizard.js"></script>
<script type="text/javascript" src="/js/ext-ux-wiz/Header.js"></script>
<script type="text/javascript" src="/js/ext-ux-wiz/Card.js"></script>
<!-- ^^ EO Ext.ux.Wiz -->

<!-- Ext.ux.grid.GridViewMenuPlugin -->
<script type="text/javascript" src="/js/ext-ux-grid-gridviewmenuplugin/GridViewMenuPlugin.js"></script>
<!-- ^^ EO Ext.ux.grid.GridViewMenuPlugin -->

<!-- Ext.ux.LiveGrid -->
<script type="text/javascript" src="/js/ext-ux-livegrid/livegrid-all-debug.js"></script>
<!-- ^^ EO Ext.ux.LiveGrid -->

<!-- CUDGETS -->
<script type="text/javascript" src="/js/conjoon/source/cudgets/localCache/Api.js"></script>

<script type="text/javascript" src="/js/conjoon/source/cudgets/localCache/Adapter.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/util/Registry.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/util/MimeIconFactory.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/grid/data/DefaultFilePanelColumnModel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/data/FileRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/data/FileSelectionMediator.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/grid/FilePanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/grid/FilePanelContextMenu.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/grid/ui/DefaultFilePanelColumnRenderer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/grid/ui/DefaultFilePanelUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/grid/ui/DefaultFilePanelContextMenuUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/grid/listener/DefaultFilePanelListener.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/grid/listener/DefaultFilePanelContextMenuListener.js"></script>

<script type="text/javascript" src="/js/conjoon/source/cudgets/tree/TreeNode.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/tree/AsyncTreeNode.js"></script>

<script type="text/javascript" src="/js/conjoon/source/cudgets/form/FileChooserButton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/form/HtmlFileChooserButton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/data/Download.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/data/Upload.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/data/HtmlUpload.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/data/JsonReader.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/data/DirectProxy.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/data/Store.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/direct/ZendProvider.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/direct/BatchedResponseHelper.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/ListView.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/settings/Container.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/settings/Dialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/settings/Card.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/settings/ui/DefaultContainerUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/settings/listener/DefaultContainerListener.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/settings/ui/DefaultDialogUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/settings/listener/DefaultDialogListener.js"></script>
<script type="text/javascript" src="/js/conjoon/source/cudgets/data/StoreSync.js"></script>
<!-- ^^ EO CUDGETS -->

<!-- com.conjoon.groupware -->
<script type="text/javascript" src="/js/conjoon/source/groupware/DefaultProvider.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/Provider.js"></script>
<!-- ^^ EO com.conjoon.groupware -->

<!-- com.conjoon.groupware.localCache -->
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/Html5Adapter.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/Dialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/CachingContainer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/SettingsContainer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/IntroductionContainer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/ui/DefaultOptionsDialogUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/ui/DefaultCachingContainerUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/ui/DefaultSettingsContainerUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/ui/DefaultIntroductionContainerUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/listener/DefaultOptionsDialogListener.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/listener/DefaultCachingContainerListener.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/listener/DefaultSettingsContainerListener.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/localCache/options/listener/DefaultIntroductionContainerListener.js"></script>
<!-- ^^ EO com.conjoon.groupware.localCache -->

<!-- com.conjoon.groupware.workbench -->
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/AboutDialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/PanelDragSource.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/Menubar.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/BookmarkController.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/ToolbarController.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/ContentPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/ClickRepeater.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/Workbench.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/tools/FeedbackDialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/tools/feedback/WelcomeCard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/tools/feedback/DataCard.js"></script>
<!-- ^^ EO com.conjoon.groupware.workbench -->

<!-- com.conjoon.groupware.workbench.dd -->
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/dd/TabDropZone.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/workbench/dd/TabDragZone.js"></script>
<!-- ^^ EO com.conjoon.groupware.workbench.dd -->

<!-- com.conjoon.groupware.DownloadManager -->
<script type="text/javascript" src="/js/conjoon/source/groupware/DownloadManager.js"></script>
<!-- ^^ EO com.conjoon.groupware.DownloadManager -->


<!-- com.conjoon.groupware.ResponseInspector -->
<script type="text/javascript" src="/js/conjoon/source/groupware/ResponseInspector.js"></script>
<!-- ^^ EO com.conjoon.groupware.ResponseInspector -->

<!-- com.conjoon.groupware.Registry -->
<script type="text/javascript" src="/js/conjoon/source/groupware/Registry.js"></script>
<!-- ^^ EO com.conjoon.groupware.ResponseInspector -->


<!-- com.conjoon.groupware.reception -->
<script type="text/javascript" src="/js/conjoon/source/groupware/reception/LogoutWindow.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/reception/LoginWindow.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/Reception.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/reception/StateIndicator.js"></script>
<!-- ^^ EO com.conjoon.groupware.reception -->

<!-- com.conjoon.groupware -->
<script type="text/javascript" src="/js/conjoon/source/groupware/StatusBar.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/NotificationManager.js"></script>
<!-- ^^ EO com.conjoon.groupware -->

<!-- com.conjoon.groupware.util -->
<script type="text/javascript" src="/js/conjoon/source/groupware/util/LinkInterceptor.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/util/FormIntro.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/util/Clear.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/util/PreviewListener.js"></script>
<!-- ^^ EO com.conjoon.groupware.util -->

<!-- com.conjoon.groupware.forms -->
<script type="text/javascript" src="/js/conjoon/source/groupware/forms/QuickContactForm.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/forms/QuickEmailForm.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/QuickEditPanel.js"></script>
<!-- ^^ EO com.conjoon.groupware.forms -->

<!-- com.conjoon.groupware.home -->
<script type="text/javascript" src="/js/conjoon/source/groupware/home/HomePanel.js"></script>
<!-- ^^ EO com.conjoon.groupware.home -->

<!-- com.conjoon.groupware.feeds -->
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/ItemRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/AccountRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/AccountStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedRunner.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedViewBaton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedPreview.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedGrid.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/AddFeedDialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedOptionsDialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/feeds/FeedGridPreviewListener.js"></script>
<!-- ^^ EO com.conjoon.groupware.feeds -->

<!-- com.conjoon.groupware.email -->
<script type="text/javascript" src="/js/conjoon/source/groupware/email/view/GridViewMenuPlugin.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/view/IntroductionPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/data/DefaultColumnModel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/data/Draft.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/data/RecipientRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/Dispatcher.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/AccountRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/AccountStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailItemRecord.js"></script>

<script type="text/javascript" src="/js/conjoon/source/groupware/email/decorator/AccountActionComp.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/FetchMenuButton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/form/RecipientComboBox.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/form/EmailEditor.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/form/EmailForm.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/form/ui/AttachmentPanelUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailEditorManager.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailViewBaton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailTreeLoader.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/account/view/MappingNodeUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/account/data/MappingTreeLoader.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/account/view/ActionFolderMappingPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/account/view/FolderMappingDialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailAccountDialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/wizard/ServerTypeCard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/wizard/ServerInboxCard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/wizard/ServerOutboxCard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailAccountWizard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/view/DefaultViewRenderer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailViewPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/view/EmailGridRowRenderer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailGrid.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailTree.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailPreview.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/NodeContextMenu.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/NodeEditor.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/PendingNodeItemRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/PendingNodeUI.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/LatestEmailsPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/Letterman.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/LatestEmailsGridListener.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/options/ReadingOptionsCard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/options/ContainerUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/options/DialogListener.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/email/EmailOptionsDialog.js"></script>
<!-- ^^ EO com.conjoon.groupware.email -->

<!-- com.conjoon.service -->
<script type="text/javascript" src="/js/conjoon/source/service/Provider.js"></script>
<!-- ^^ EO com.conjoon.service -->

<!-- com.conjoon.service.twitter -->
<script type="text/javascript" src="/js/conjoon/source/service/twitter/OptionsDialog.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/optionsDialog/ContainerUi.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/optionsDialog/ContainerListener.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/optionsDialog/SettingsCard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/optionsDialog/DialogListener.js"></script>

<script type="text/javascript" src="/js/conjoon/source/service/twitter/data/AccountRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/data/AccountStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/wizard/AccountWizard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/wizard/AccountWizardBaton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/wizard/AccountCard.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/wizard/FinishCard.js"></script>

<script type="text/javascript" src="/js/conjoon/source/service/twitter/data/TweetRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/data/AccountRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/data/AccountStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/data/TweetStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/data/TwitterUserRecord.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/data/TwitterUserStore.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/data/TweetPoller.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/AccountButton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/DataView.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/InputBox.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/RecentTweetsContainer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/TwitterUserContainer.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/HomePanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/TwitterPanel.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/UserInfoBox.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/TweetList.js"></script>
<script type="text/javascript" src="/js/conjoon/source/service/twitter/FriendsList.js"></script>
<!-- ^^ EO com.conjoon.service.twitter -->

<!-- com.conjoon.groupware.service.TwitterPanel -->
<script type="text/javascript" src="/js/conjoon/source/groupware/service/TwitterPanel.js"></script>
<!-- ^^ EO com.conjoon.groupware.service.TwitterPanel -->

<!-- com.conjoon.groupware.service.youtube -->
<script type="text/javascript" src="/js/conjoon/source/groupware/service/youtube/ViewBaton.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/service/youtube/VideoDirector.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/service/youtube/FeaturePanel.js"></script>
<!-- ^^ EO com.conjoon.groupware.service.youtube -->


<!-- com.conjoon.groupware.SystemSoundManager -->
<script type="text/javascript" src="/js/conjoon/source/groupware/SystemSoundManager.js"></script>
<!-- ^^ EO com.conjoon.groupware.SystemSoundManager -->

<!-- soundmanager 2 -->
<script type="text/javascript" src="/js/soundmanager/script/soundmanager2.js"></script>
<!-- ^^ EO soundmanager 2 -->

<!-- STARTUP -->
<script type="text/javascript" src="./startup.js"></script>
<!-- ^^ EO STARTUP -->
<?php /*@REMOVE@*/ ?>
