<?php
/**
 * conjoon
 * (c) 2002-2010 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<div  id="DOM:com.conjoon.groupware.Startup" class="com-conjoon-groupware-SplashScreen">

 <div id="DOM:com.conjoon.groupware.Startup.body" class="wrap">
  <div class="x-shadow" style="margin-top:-150px;margin-left:-248px;z-index: 9002; left: 50%; top: 50%; height:330px;width:502px; display: block;">
   <div class="xst">
    <div class="xstl"></div>
    <div class="xstc" style="width: 490px;"></div>
    <div class="xstr"></div>
   </div>
   <div class="xsc" style="height: 322px;">
    <div class="xsml"></div>
    <div class="xsmc" style="width: 490px;"></div>
    <div class="xsmr"></div>
   </div>
   <div class="xsb">
    <div class="xsbl"></div>
    <div class="xsbc" style="width: 490px;"></div>
    <div class="xsbr"></div>
   </div>
  </div>

  <div class="x-window" style="z-index: 9003;position:absolute;left:50%;top:50%;margin-top:-157px;margin-left:-248px;height:315px;width:494px;">
   <div class="x-window-tl x-panel-noheader"><div class="x-window-tr"><div class="x-window-tc" style="height:8px;"></div></div></div>
    <div class="x-window-bwrap">
     <div class="x-window-ml"><div class="x-window-mr"><div class="x-window-mc">
      <div class="body">
       <div style="padding:5px;font-size:12px;font-weight:bold;color:#2D5094">conjoon</div>
       <div style="position:absolute;top:55px;left:145px;width:220px;height:50px;color:#2D5094">
        <div style="padding-left:10px;padding-bottom:10px;">Please wait...</div>
        <div class="loadingCont" id="com.conjoon.groupware.Startup.loadingCont" style="padding-left:10px;padding-bottom:10px;height:110px;overflow:auto">
        </div>
        <div class="progressBar">&nbsp;</div>
       </div>
       <div class="errorPanel" id="errorPanel">
         <div class="textContainer">
             <span class="notice" id="error-notice"></span>
             <div class="message" id="error-message"></div>
         </div>
       </div>
       </div>
      </div>
     </div>
    </div>
   </div>
   <div class="x-window-bl x-panel-nofooter"><div class="x-window-br"><div class="x-window-bc"></div></div></div>
  </div>

 </div>
</div>