<?php
/**
 * conjoon
 * (c) 2007-2014 conjoon.org
 * licensing@conjoon.org
 *
 * conjoon
 * Copyright (C) 2014 Thorsten Suckow-Homberg/conjoon.org
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<div  id="cn_startup_splash" class="cn-splashScreen">

    <div class="errorPanel" id="cn_startup_splash_errorPanel">
        <div class="textContainer">
            <span class="notice" id="cn_startup_splash_errorPanel_errorNotice"></span>
            <div class="message" id="cn_startup_splash_errorPanel_errorMessage"></div>
        </div>
    </div>


    <div id="cn_startup_splash_body" class="body">
        <div id="cn_startup_splash_body_greetingCont" class="greetingCont">Welcome back, Thorsten!</div>
        <div>
            <span>conjoon</span>
            <div class="loadingCont" id="cn_startup_splash_body_loadingCont">
            </div>
        </div>

    </div>


</div>