<?php
/**
 * conjoon
 * (c) 2007-2014 conjoon.org
 * licensing@conjoon.org
 *
 * conjoon
 * Copyright (C) 2014 Thorsten Suckow-Homberg/conjoon.org
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>


<div id="DOM:com.conjoon.groupware.Startup" class="com-conjoon-groupware-SplashScreen-wrap">
 <div class="x-window" style="z-index: 9003;position:absolute;left:50%;top:50%;margin-top:-162px;margin-left:-140px;height:315px;width:280px;">
  <div class="x-window-tl x-panel-noheader"><div class="x-window-tr"><div class="x-window-tc" style="height:8px;"></div></div></div>
   <div class="x-window-bwrap">
    <div class="x-window-ml"><div class="x-window-mr"><div class="x-window-mc">
     <div class="com-conjoon-groupware-SplashScreen-body">
      <div style="padding:5px;font-size:12px;font-weight:bold;color:#2D5094">conjoon iPhone</div>
      <div style="position:absolute;top:135px;left:32px;width:220px;height:50px;color:#2D5094">
       <div style="padding-left:10px;padding-bottom:10px;">Please wait...</div>
       <div class="com-conjoon-groupware-SplashScreen-progressBar">&nbsp;</div>
      </div>
      </div>
     </div>
    </div>
   </div>
  </div>
  <div class="x-window-bl x-panel-nofooter"><div class="x-window-br"><div class="x-window-bc"></div></div></div>
 </div>

</div>