<?php
/**
 * conjoon
 * (c) 2002-2012 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<div  id="cn_startup_splash" class="cn-splashScreen">

    <div class="errorPanel" id="cn_startup_splash_errorPanel">
        <div class="textContainer">
            <span class="notice" id="cn_startup_splash_errorPanel_errorNotice"></span>
            <div class="message" id="cn_startup_splash_errorPanel_errorMessage"></div>
        </div>
    </div>


    <div id="cn_startup_splash_body" class="body">
        <div id="cn_startup_splash_body_greetingCont" class="greetingCont">Welcome back, Thorsten!</div>
        <div>
            <span>conjoon</span>
            <div class="loadingCont" id="cn_startup_splash_body_loadingCont">
            </div>
        </div>

    </div>


</div>