<?php
/**
 * conjoon
 * (c) 2002-2010 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>


<div id="DOM:com.conjoon.groupware.Startup" class="com-conjoon-groupware-SplashScreen-wrap">
 <div class="x-window" style="z-index: 9003;position:absolute;left:50%;top:50%;margin-top:-162px;margin-left:-140px;height:315px;width:280px;">
  <div class="x-window-tl x-panel-noheader"><div class="x-window-tr"><div class="x-window-tc" style="height:8px;"></div></div></div>
   <div class="x-window-bwrap">
    <div class="x-window-ml"><div class="x-window-mr"><div class="x-window-mc">
     <div class="com-conjoon-groupware-SplashScreen-body">
      <div style="padding:5px;font-size:12px;font-weight:bold;color:#2D5094">conjoon iPhone</div>
      <div style="position:absolute;top:135px;left:32px;width:220px;height:50px;color:#2D5094">
       <div style="padding-left:10px;padding-bottom:10px;">Please wait...</div>
       <div class="com-conjoon-groupware-SplashScreen-progressBar">&nbsp;</div>
      </div>
      </div>
     </div>
    </div>
   </div>
  </div>
  <div class="x-window-bl x-panel-nofooter"><div class="x-window-br"><div class="x-window-bc"></div></div></div>
 </div>

</div>