<?php
/**
 * conjoon
 * (c) 2002-2009 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author: T. Suckow $
 * $Id: _stylesheets.phtml 337 2008-12-16 21:59:59Z T. Suckow $
 * $Date: 2008-12-16 22:59:59 +0100 (Di, 16 Dez 2008) $
 * $Revision: 337 $
 * $LastChangedDate: 2008-12-16 22:59:59 +0100 (Di, 16 Dez 2008) $
 * $LastChangedBy: T. Suckow $
 * $URL: file:///F:/live/vs170240.vserver.de/svn_repository/conjoon/trunk/src/www/application/modules/default/views/scripts/index/_stylesheets.phtml $
 */
?>

<!-- base -->
<link rel="stylesheet" type="text/css" href="./js/extjs/resources/css/ext-all.css" />
<!-- ^^ EO base -->



<link rel="stylesheet" type="text/css" href="./js/conjoon/resources/css/conjoon-all.css" />

<link rel="stylesheet" type="text/css" href="./js/conjoon/resources/themes/iphone/iphone.css" />