<?php
/**
 * conjoon
 * (c) 2007-2015 conjoon.org
 * licensing@conjoon.org
 *
 * conjoon
 * Copyright (C) 2014 Thorsten Suckow-Homberg/conjoon.org
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<!-- base -->
<link rel="stylesheet" type="text/css" href="./js/extjs/resources/css/ext-all.css" />
<!-- ^^ EO base -->


<!-- Extension Styles -->
<link rel="stylesheet" type="text/css" href="./js/ext-ux-grid-gridviewmenuplugin/resources/css/ext-ux-grid-gridviewmenuplugin.css" />
<link rel="stylesheet" type="text/css" href="./js/ext-ux-youtubeplayer/resources/css/ext-ux-youtubeplayer.css" />
<link rel="stylesheet" type="text/css" href="./js/ext-ux-youtubeplayer/resources/css/ext-ux-youtubeplayer-control.css" />
<link rel="stylesheet" type="text/css" href="./js/ext-ux-toastwindow/css/ext-ux-toastwindow.css" />
<link rel="stylesheet" type="text/css" href="./js/ext-ux-livegrid/resources/css/ext-ux-livegrid.css" />
<link rel="stylesheet" type="text/css" href="./js/ext-ux-wiz/resources/css/ext-ux-wiz.css" />
<link rel="stylesheet" type="text/css" href="./js/ext-ux-flexaccord/resources/css/ext-ux-flexaccord.css" />
<link rel="stylesheet" type="text/css" href="./js/ext-ux-flashcontrol/resources/css/ext-ux-flashcontrol.css" />
<!-- ^^ EO Extension Styles -->

<link rel="stylesheet" type="text/css" href="./js/conjoon/resources/css/conjoon-all.css" />