<?php
/**
 * intrabuild
 * (c) 2002-2008 siteartwork.de/MindPatterns
 * license@siteartwork.de
 *
 * $Author$
 * $Id$
 * $Date$ 
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$ 
 */
?>

<!-- base --> 
<link rel="stylesheet" type="text/css" href="/js/extjs/resources/css/ext-all.css"/>
<!-- ^^ EO base --> 

<!-- Extension Styles --> 
<link rel="stylesheet" type="text/css" href="/js/ext-ux-youtubeplayer/resources/css/ext-ux-youtubeplayer.css" />
<link rel="stylesheet" type="text/css" href="/js/ext-ux-toastwindow/css/ext-ux-toastwindow.css" />
<link rel="stylesheet" type="text/css" href="/js/ext-ux-livegrid/resources/css/ext-ux-livegrid.css" />
<link rel="stylesheet" type="text/css" href="/js/ext-ux-wiz/resources/css/ext-ux-wiz.css" />
<!-- ^^ EO Extension Styles --> 

<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-StatusBar.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-ProgressBar.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/default-all.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-feeds.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-email-LatestEmailsPanel.css" />

<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-email-EmailAccountDialog.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-email-EmailAccountWizard.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-email-EmailEditorManager.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-email-EmailGrid.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-email-EmailPanel.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-email-EmailView.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-email-EmailTree.css" />

<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-feeds-AddFeedDialog.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-feeds-FeedGrid.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-feeds-FeedPreview.css" />
<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-feeds-FeedViewBaton.css" />

<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-util-MimeIconFactory.css" />

<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-SplashScreen.css" />

<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware.css" />

<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/de-intrabuild-groupware-HomePanel.css" />