<?php
/**
 * conjoon
 * (c) 2002-2009 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
    <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title><?php echo $this->title; ?></title>
    <link rel="shortcut icon" href="./favicon.png" type="image/png" />
    <?php echo $this->render('index/_stylesheets.phtml'); ?>

</head>

<body>

<?php echo $this->render('index/_splashscreen.phtml'); ?>

<?php echo $this->render('index/_scripts.phtml'); ?>

</body>
</html>