<?php
/**
 * intrabuild
 * (c) 2002-2008 siteartwork.de/MindPatterns
 * license@siteartwork.de
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */

?>
<!DOCTYPE htmlPUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
 <head>
  <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>intraBuild 2.0 - js sandbox</title>
  <?php echo $this->render('index/_stylesheets.phtml'); ?>

  <!-- Custom Styles -->
  <style type="text/css">

  </style>
  <!-- ^^ EO Custom Styles -->
 </head>

 <body>
  <?php echo $this->render('index/_scripts.phtml'); ?>

<script type="text/javascript">

Ext.onReady(function(){


    Ext.BLANK_IMAGE_URL = "/libraries/ext/resources/images/default/s.gif";
    Ext.QuickTips.init();


    var a = [0, 1, 2, 3, 4, 5];

    var b = a.splice(0,3);

    alert(b.length+" "+a.length);

    /*var w = new Ext.Window({
        laxout : 'fit',
        height : 400,
        width:300,
        items : [
           new de.intrabuild.groupware.email.EmailTree({
            })
        ]

    });
    w.show();*/

    /*de.intrabuild.util.PreLoader.on('load', function() {
        var w = new Ext.Window({
            height: 500,
            layout:'fit',
            width:400,
            items:[
                new de.intrabuild.groupware.feeds.FeedGrid()
            ]

        });
        w.show();

    });

    de.intrabuild.util.PreLoader.load();*/

});


</script>


</body>
</html>