<?php
/**
 * intrabuild
 * (c) 2002-2008 siteartwork.de/MindPatterns
 * license@siteartwork.de
 *
 * $Author: T. Suckow $
 * $Id: _stylesheets.phtml 12 2008-06-28 00:43:33Z T. Suckow $
 * $Date: 2008-06-28 02:43:33 +0200 (Sa, 28 Jun 2008) $
 * $Revision: 12 $
 * $LastChangedDate: 2008-06-28 02:43:33 +0200 (Sa, 28 Jun 2008) $
 * $LastChangedBy: T. Suckow $
 * $URL: file:///F:/svn_repository/intrabuild/trunk/src/www/application/modules/default/views/scripts/index/_stylesheets.phtml $
 */
?>

<!-- base -->
<link rel="stylesheet" type="text/css" href="/js/extjs/resources/css/ext-all.css" />
<!-- ^^ EO base -->

<link rel="stylesheet" type="text/css" href="/js/intrabuild/resources/css/intrabuild-all.css" />