<?php
/**
 * conjoon
 * (c) 2002-2009 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */

/**
 * Will sum up all the installation data and install conjoon upon a post request.
 *
 * @author Thorsten Suckow-Homberg <ts@siteartwork.de>
 */

$INSTALL = array();

$INSTALL['include_path']['ini'] = rtrim($_SESSION['lib_path'], '/')
                                  . '/'
                                  . $_SESSION['setup_ini']['lib_path']['folder'];

$INSTALL['include_path']['delete'] = explode(",", $_SESSION['setup_ini']['lib_path']['delete']);

$INSTALL['app_path']['full']   = rtrim($_SESSION['app_path'], '/')
                                  . '/'
                                  . $_SESSION['setup_ini']['app_path']['folder'];
$INSTALL['app_path']['delete'] = explode(",", $_SESSION['setup_ini']['app_path']['delete']);

$INSTALL['include_path']['delete_warning'] = false;
$INSTALL['app_path']['delete_warning']     = false;

if (file_exists($INSTALL['app_path']['full'])) {
    $INSTALL['app_path']['delete_warning'] = true;
}

if (file_exists($INSTALL['include_path']['ini'])) {
    $INSTALL['include_path']['delete_warning'] = true;
}

if (isset($_POST['install_post'])) {

    // proceed installation. First of, generate .htaccess
    $htaccess = file_get_contents('./htaccess.template');
    $htaccess = str_replace("{REWRITE_BASE}", $_SESSION['doc_path'], $htaccess);
    file_put_contents('../.htaccess', $htaccess);
    $htaccess = "";

    $libFolder = $_SESSION['setup_ini']['lib_path']['folder'];
    $appFolder = $_SESSION['setup_ini']['app_path']['folder'];

    // generate config.ini.php
    $configini = file_get_contents('./config.ini.php.template');

    if ($_SESSION['add_include_path']) {
        $configini = str_replace(
            "{INCLUDE_PATH}",
            $_SESSION['lib_path'] . "/" . $libFolder,
            $configini
        );
    } else {
        $configini = str_replace("{INCLUDE_PATH}", "", $configini);
    }

    $configini = str_replace(
        "{APPLICATION_PATH}",
        $_SESSION['app_path'] . '/' . $_SESSION['setup_ini']['app_path']['folder'],
        $configini
    );
    $configini = str_replace("{BASE_URL}", $_SESSION['doc_path'], $configini);
    $configini = str_replace("{EDITION}", '"' . $_SESSION['edition']. '"', $configini);
    $configini = str_replace("{DATABASE.ADAPTER}", $_SESSION['db_adapter'], $configini);
    $configini = str_replace("{DATABASE.HOST}", $_SESSION['db_host'], $configini);
    $configini = str_replace("{DATABASE.PORT}", $_SESSION['db_port'], $configini);
    $configini = str_replace("{DATABASE.USER}", $_SESSION['db_user'], $configini);
    $configini = str_replace("{DATABASE.PASSWORD}", $_SESSION['db_password'], $configini);
    $configini = str_replace("{DATABASE.DATABASE}", $_SESSION['db'], $configini);
    $configini = str_replace("{DATABASE_MAX_ALLOWED_PACKET}", $_SESSION['max_allowed_packet'], $configini);
    file_put_contents('../config.ini.php', $configini);
    $configini = "";

    // generate and update install.info.php
    if (!file_exists('../installation.info.php')) {
        $installationinfo = file_get_contents('./installation.info.php.template');
    } else {
        $installationinfo = file_get_contents('../installation.info.php');
    }
    $installationinfo .= "\n
        // generated by conjoon V".$_SESSION['current_version']."
        // on ".date("m-d-Y H:i:s", time())."
        \$INSTALLATION_INFO[] = array(
            'support_key'        => '".$_SESSION['support_key']."',
            'version'            => '".$_SESSION['current_version']."',
            'date'               => '".time()."',
            'db_host'            => '".$_SESSION['db_host']."',
            'db_adapter'         => '".$_SESSION['db_adapter']."',
            'db'                 => '".$_SESSION['db']."',
            'db_port'            => '".$_SESSION['db_port']."',
            'db_user'            => '".$_SESSION['db_user']."',
            'edition'            => '".$_SESSION['edition']."',
            'max_allowed_packet' => '".$_SESSION['max_allowed_packet']."',
            'app_path'           => '".$_SESSION['app_path']."',
            'lib_path'           => '".$_SESSION['lib_path']."',
            'add_include_path'   => '".$_SESSION['add_include_path']."',
            'doc_path'           => '".$_SESSION['doc_path']."',
            'app_credentials'    => array('user' => '".$_SESSION['app_credentials']['user']."')
        );
    ";

    file_put_contents('../installation.info.php', $installationinfo);
    $installationinfo = "";

    // import the sql file for the selected database
    $path = realpath('./files/datastore/mysql/conjoon.sql');
    conjoon_createTables($path, $_SESSION['db_adapter'], array(
        'host'     => $_SESSION['db_host'],
        'port'     => $_SESSION['db_port'],
        'database' => $_SESSION['db'],
        'user'     => $_SESSION['db_user'],
        'password' => $_SESSION['db_password']
    ));
    $table = "";
    sleep(1);
    // create root user if needed
    if (!isset($_SESSION['installation_info']['app_credentials'])) {
        conjoon_createAdmin($_SESSION['db_adapter'], array(
            'user'          => $_SESSION['app_credentials']['user'],
            'password'      => $_SESSION['app_credentials']['password'],
            'firstname'     => $_SESSION['app_credentials']['firstname'],
            'lastname'      => $_SESSION['app_credentials']['lastname'],
            'email_address' => $_SESSION['app_credentials']['email_address']
        ), array(
            'host'     => $_SESSION['db_host'],
            'port'     => $_SESSION['db_port'],
            'database' => $_SESSION['db'],
            'user'     => $_SESSION['db_user'],
            'password' => $_SESSION['db_password']
        ));
    }

    // move libs folders
    $libFolders = explode(",", $_SESSION['setup_ini']['lib_path']['delete']);
    for ($i = 0, $len = count($libFolders); $i < $len; $i++) {
        $libFolders[$i] = trim($libFolders[$i]);
        conjoon_rmdir($_SESSION['lib_path'] . "/" . $libFolder . "/" . $libFolders[$i]);
        rmdir($_SESSION['lib_path'] . "/" . $libFolder . "/" . $libFolders[$i]);
        if (!file_exists($_SESSION['lib_path'] . "/" . $libFolder)) {
            mkdir($_SESSION['lib_path'] . "/" . $libFolder);
        }
        if (file_exists('./files/' . $libFolder . "/" . $libFolders[$i])) {
            rename(
                './files/' . $libFolder . "/" . $libFolders[$i],
                $_SESSION['lib_path'] . "/" . $libFolder . "/" . $libFolders[$i]
            );
        }
    }

    // move application folders
    $appFolders = explode(",", $_SESSION['setup_ini']['app_path']['delete']);
    for ($i = 0, $len = count($appFolders); $i < $len; $i++) {
        $appFolders[$i] = trim($appFolders[$i]);
        conjoon_rmdir($_SESSION['app_path'] . "/" . $appFolder . "/" . $appFolders[$i]);
        rmdir($_SESSION['app_path'] . "/" . $appFolder . "/" . $appFolders[$i]);
        if (!file_exists($_SESSION['app_path'] . "/" . $appFolder)) {
            mkdir($_SESSION['app_path'] . "/" . $appFolder);
        }
        if (file_exists('./files/' . $appFolder . "/" . $appFolders[$i])) {
            rename(
                './files/' . $appFolder . "/" . $appFolders[$i],
                $_SESSION['app_path'] . "/" . $appFolder . "/" . $appFolders[$i]
            );
        }
    }

    header("Location: ./?action=install_success");
    die();
}

include_once './view/install.tpl';