<?php
/**
 * conjoon
 * (c) 2002-2012 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<?php /*@BUILD_ACTIVE@
<script type="text/javascript" src="./js/extjs/ext-base.js"></script>
<script type="text/javascript" src="./js/extjs/ext-all.js"></script>
<script type="text/javascript" src="./js/conjoon/conjoon-login.js"></script>
@BUILD_ACTIVE@*/ ?>


<?php /*@REMOVE@*/ ?>
 <!-- base -->
<script type="text/javascript" src="/js/extjs/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="/js/extjs/ext-all-debug.js"></script>
<!-- ^^ EO base -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="./ext-config.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="/js/conjoon/source/Overrides.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- iPhone Overrides -->
<script type="text/javascript" src="/js/conjoon/source/iphone/Overrides.js"></script>
<!-- ^^ EO iPhone Overrides -->


<!-- Load Gettext since other sources may depend on it -->
<script type="text/javascript" src="/js/conjoon/source/Gettext.js"></script>
<!-- ^^ EO Load Gettext since other sources may depend on it -->

<!-- com.conjoon.util -->
<script type="text/javascript" src="/js/conjoon/source/util/Json.js"></script>
<!-- ^^ EO com.conjoon.util -->

<!-- com.conjoon.form -->
<script type="text/javascript" src="/js/conjoon/source/form/TextField.js"></script>
<!-- ^^ EO com.conjoon.form -->

<!-- com.conjoon.groupware.Registry -->
<script type="text/javascript" src="/js/conjoon/source/groupware/Registry.js"></script>
<!-- ^^ EO com.conjoon.groupware.Registry -->

<!-- com.conjoon.groupware.util -->
<script type="text/javascript" src="/js/conjoon/source/util/PreLoader.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/util/FormIntro.js"></script>
<!-- ^^ EO com.conjoon.groupware.util -->

<!-- Ext.ux.util.Messagebus -->
<script type="text/javascript" src="/js/ext-ux-util-messagebus/MessageBus.js"></script>
<!-- ^^ EO Ext.ux.util.Messagebus -->

<!-- com.conjoon.groupware.ResponseInspector -->
<script type="text/javascript" src="/js/conjoon/source/groupware/ResponseInspector.js"></script>
<!-- ^^ EO com.conjoon.groupware.ResponseInspector -->

<!-- Load SystemMessage-classes -->
<script type="text/javascript" src="/js/conjoon/source/SystemMessage.js"></script>
<script type="text/javascript" src="/js/conjoon/source/SystemMessageManager.js"></script>
<!-- ^^ EO Load SystemMessage-classes -->

<!-- com.conjoon.groupware.reception -->
<script type="text/javascript" src="/js/conjoon/source/groupware/reception/LoginWindow.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/reception/StateIndicator.js"></script>
<script type="text/javascript" src="/js/conjoon/source/groupware/Reception.js"></script>
<!-- ^^ EO com.conjoon.groupware.reception -->

<!-- com.conjoon.iphone.groupware.reception -->
<script type="text/javascript" src="/js/conjoon/source/iphone/groupware/reception/LoginWindow.js"></script>
<!-- ^^ EO com.conjoon.iphone.groupware.reception -->

<?php /*@REMOVE@*/ ?>
