<?php
/**
 * intrabuild
 * (c) 2002-2008 siteartwork.de/MindPatterns
 * license@siteartwork.de
 *
 * $Author: T. Suckow $
 * $Id: _scripts.phtml 2 2008-06-21 10:38:49Z T. Suckow $
 * $Date: 2008-06-21 12:38:49 +0200 (Sa, 21 Jun 2008) $
 * $Revision: 2 $
 * $LastChangedDate: 2008-06-21 12:38:49 +0200 (Sa, 21 Jun 2008) $
 * $LastChangedBy: T. Suckow $
 * $URL: file:///F:/svn_repository/intrabuild/trunk/src/www/application/modules/default/views/scripts/index/_scripts.phtml $
 */
?>

<!-- ########################################################################################## -->

<!-- base -->
<script type="text/javascript" src="/js/extjs/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="/js/extjs/ext-all-debug.js"></script>
<!-- ^^ EO base -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="./ext-config.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="/js/intrabuild/source/Overrides.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- de.intrabuild.util -->
<script type="text/javascript" src="/js/intrabuild/source/util/Json.js"></script>
<!-- ^^ EO de.intrabuild.util -->

<!-- de.intrabuild.form -->
<script type="text/javascript" src="/js/intrabuild/source/form/TextField.js"></script>
<!-- ^^ EO de.intrabuild.form -->

<!-- de.intrabuild.groupware.util -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/util/FormIntro.js"></script>
<!-- ^^ EO de.intrabuild.groupware.util -->

<!-- Ext.ux.util.Messagebus -->
<script type="text/javascript" src="/js/ext-ux-util-messagebus/MessageBus.js"></script>
<!-- ^^ EO Ext.ux.util.Messagebus -->

<!-- de.intrabuild.groupware.ResponseInspector -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/ResponseInspector.js"></script>
<!-- ^^ EO de.intrabuild.groupware.ResponseInspector -->

<!-- de.intrabuild.groupware.reception -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/Reception.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/reception/LoginWindow.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/reception/StateIndicator.js"></script>
<!-- ^^ EO de.intrabuild.groupware.reception -->