<?php
/**
 * conjoon
 * (c) 2002-2009 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<!-- ########################################################################################## -->

<!-- base -->
<script type="text/javascript" src="/js/extjs/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="/js/extjs/ext-all-debug.js"></script>
<!-- ^^ EO base -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="./ext-config.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load common overrides for the project -->
<script type="text/javascript" src="/js/intrabuild/source/Overrides.js"></script>
<!-- ^^ EO Load common overrides for the project -->

<!-- Load Gettext since other sources may depend on it -->
<script type="text/javascript" src="/js/intrabuild/source/Gettext.js"></script>
<!-- ^^ EO Load Gettext since other sources may depend on it -->

<!-- de.intrabuild.util -->
<script type="text/javascript" src="/js/intrabuild/source/util/Json.js"></script>
<!-- ^^ EO de.intrabuild.util -->

<!-- de.intrabuild.form -->
<script type="text/javascript" src="/js/intrabuild/source/form/TextField.js"></script>
<!-- ^^ EO de.intrabuild.form -->

<!-- de.intrabuild.groupware.Registry -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/Registry.js"></script>
<!-- ^^ EO de.intrabuild.groupware.Registry -->

<!-- de.intrabuild.groupware.util -->
<script type="text/javascript" src="/js/intrabuild/source/util/PreLoader.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/util/FormIntro.js"></script>
<!-- ^^ EO de.intrabuild.groupware.util -->

<!-- Ext.ux.util.Messagebus -->
<script type="text/javascript" src="/js/ext-ux-util-messagebus/MessageBus.js"></script>
<!-- ^^ EO Ext.ux.util.Messagebus -->

<!-- de.intrabuild.groupware.ResponseInspector -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/ResponseInspector.js"></script>
<!-- ^^ EO de.intrabuild.groupware.ResponseInspector -->

<!-- de.intrabuild.groupware.reception -->
<script type="text/javascript" src="/js/intrabuild/source/groupware/Reception.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/reception/LoginWindow.js"></script>
<script type="text/javascript" src="/js/intrabuild/source/groupware/reception/StateIndicator.js"></script>
<!-- ^^ EO de.intrabuild.groupware.reception -->