<?php
/**
 * conjoon
 * (c) 2007-2015 conjoon.org
 * licensing@conjoon.org
 *
 * conjoon
 * Copyright (C) 2014 Thorsten Suckow-Homberg/conjoon.org
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>
<!DOCTYPE html>

<html>
 <head>
  <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <link rel="shortcut icon" href="./favicon.png" type="image/png" />
  <title><?php echo $this->title; ?></title>

  <?php echo $this->render('reception/_stylesheets.phtml'); ?>


 </head>

 <body class="com-conjoon-groupware-Reception-body">

<?php echo $this->render('reception/_scripts.phtml'); ?>

<script type="text/javascript">


Ext.onReady(function(){

    com.conjoon.groupware.Registry = new com.conjoon.cudgets.direct.Registry({
        directProvider : com.conjoon.defaultProvider.registry
    });

    com.conjoon.groupware.Registry.load({
        fn : function() {
            com.conjoon.groupware.Reception.init(false);

            com.conjoon.SystemMessageManager.setContext(com.conjoon.groupware.Registry.get(
                '/client/environment/device'
            ));
        }
    });



});
  </script>
 </body>

</html>
