<?php
/**
 * conjoon
 * (c) 2002-2010 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<!DOCTYPE htmlPUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
 <head>
  <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <link rel="shortcut icon" href="./favicon.png" type="image/png" />
  <title><?php echo $this->title; ?></title>

  <?php echo $this->render('reception/_stylesheets.phtml'); ?>


 </head>

 <body class="com-conjoon-groupware-Reception-body">

<?php echo $this->render('reception/_scripts.phtml'); ?>

<script type="text/javascript">


Ext.onReady(function(){

    com.conjoon.util.PreLoader.addStore(com.conjoon.groupware.Registry.getStore());

    com.conjoon.util.PreLoader.on('load', function() {
        var reception = com.conjoon.groupware.Reception;
        reception.init(false);

        com.conjoon.SystemMessageManager.setContext(com.conjoon.groupware.Registry.get(
            '/client/environment/device'
        ));
    });

    com.conjoon.util.PreLoader.load();
});
  </script>
 </body>

</html>