<?php
/**
 * conjoon
 * (c) 2002-2012 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>
<!DOCTYPE html>

<html>
 <head>
  <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title><?php echo $this->title; ?></title>
  <link rel="shortcut icon" href="./favicon.png" type="image/png" />
  <?php echo $this->render('reception/_stylesheets.phtml'); ?>


 </head>

 <body class="com-conjoon-groupware-Reception-body">

<?php echo $this->render('reception/_scripts.phtml'); ?>

<script type="text/javascript">


Ext.onReady(function(){

    com.conjoon.groupware.Registry.load({
        fn : function() {
            var reception = com.conjoon.groupware.Reception;
            reception.init(false);

            com.conjoon.SystemMessageManager.setContext(com.conjoon.groupware.Registry.get(
                '/client/environment/device'
            ));

            <?php if ($this->locked === true) { ?>
                reception.onUserLoad(function(){
                    reception.showLogin(reception.TYPE_UNLOCK);
                });
            <?php } else { ?>
                reception.showLogin(reception.TYPE_LOGIN);
            <?php } ?>
        }
    });


});
  </script>
 </body>

</html>