<?php
/**
 * conjoon
 * (c) 2007-2015 conjoon.org
 * licensing@conjoon.org
 *
 * conjoon
 * Copyright (C) 2014 Thorsten Suckow-Homberg/conjoon.org
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<!DOCTYPE htmlPUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
 <head>
  <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <link rel="shortcut icon" href="./favicon.png" type="image/png" />
  <title><?php echo $this->title; ?></title>

  <?php echo $this->render('reception/_stylesheets.iphone.phtml'); ?>


 </head>

 <body class="com-conjoon-groupware-Reception-body">

<?php echo $this->render('reception/_scripts.iphone.phtml'); ?>

<script type="text/javascript">


Ext.onReady(function(){

    com.conjoon.util.PreLoader.addStore(com.conjoon.groupware.Registry.getStore());

    com.conjoon.util.PreLoader.on('load', function() {

        var w = new Ext.Viewport();

        var reception = com.conjoon.groupware.Reception;
        reception.init(false, {
            loginWindowClass : com.conjoon.iphone.groupware.reception.LoginWindow
        });

        <?php if ($this->locked === true) { ?>
            reception.onUserLoad(function(){
                reception.showLogin(reception.TYPE_UNLOCK);
            });
        <?php } else { ?>
            reception.showLogin(reception.TYPE_LOGIN);
        <?php } ?>
    });

    com.conjoon.util.PreLoader.load();
});
  </script>
 </body>

</html>