<?php
/**
 * conjoon
 * (c) 2002-2009 siteartwork.de/conjoon.org
 * licensing@conjoon.org
 *
 * $Author$
 * $Id$
 * $Date$
 * $Revision$
 * $LastChangedDate$
 * $LastChangedBy$
 * $URL$
 */
?>

<!DOCTYPE htmlPUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
 <head>
  <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title><?php echo $this->title; ?></title>

  <?php echo $this->render('reception/_stylesheets.phtml'); ?>


 </head>

 <body class="de-intrabuild-groupware-Reception-body">

<?php echo $this->render('reception/_scripts.phtml'); ?>

<script type="text/javascript">


Ext.onReady(function(){

    de.intrabuild.util.PreLoader.addStore(de.intrabuild.groupware.Registry.getStore());

    de.intrabuild.util.PreLoader.on('load', function() {
        var reception = de.intrabuild.groupware.Reception;
        reception.init(false);

        <?php if ($this->locked === true) { ?>
            reception.onUserLoad(function(){
                reception.showLogin(reception.TYPE_UNLOCK);
            });
        <?php } else { ?>
            reception.showLogin(reception.TYPE_LOGIN);
        <?php } ?>
    });

    de.intrabuild.util.PreLoader.load();
});
  </script>
 </body>

</html>